[package]
name = "cloudflare-ddns"
version = "1.0.0"
edition = "2021"

[dependencies]
env_logger = "0.9"
log = "0.4"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
