# Your root domain without subdomain
zone_name = "example.com"

# Cloudflare API token with DNS edit access to the zone.
# These can be made at https://dash.cloudflare.com/profile/api-tokens.
api_token = "your-token"

# The name of the record(s) which should be monitored and updated.
# For example "ddns" would keep the record(s) pointing to "ddns.example.com" updated.
# A value of "@" stands for the root domain (in this example "example.com")
record_name = "@"

# The interval in seconds between updating the record(s).
# If set to 0, the timer is disabled and the script runs just once.
interval = 0

# Create and remove records based on the availability of IPs on the machine.
# For example, when an IPv6 address is detected but there is no AAAA record, create one.
# And for example when there is an A record but the machine doesn't have an IPv4 address, delete it.
# When creating a record, it copies the proxy status and TTL from the other record if present.
manage_records = false
